bookmark.user: string -> integer
This is needed because postgres can't automatically convert string to
integer and retrieving bookmarks fails with the following error.

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: character varying = integer
LINE 3: WHERE bookmark."user" = 1
                              ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
 [SQL: 'SELECT bookmark.id AS bookmark_id, bookmark."user" AS bookmark_user, bookmark.timestamp AS bookmark_timestamp, bookmark.url AS bookmark_url, bookmark.title AS bookmark_title, bookmark.read AS bookmark_read \nFROM bookmark \nWHERE bookmark."user" = %(user_1)s \n LIMIT %(param_1)s OFFSET %(param_2)s'] [parameters: {'param_2': 0, 'param_1': 20, 'user_1': 1}]
```