Declare postgresql as Heroku dependency
Problem: Heroku fails to deploy PR.
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

This is caused by database not being present in the deployment.

Solution: declare postgresql database as a dependency and move its
initialization to release phase (as recommended by Heroku).