Add redis on Travis
Problem: redis is required for tests to pass.
```
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```

Solution: add redis to travis environment.